sbatch generate_partial_precomp_camelyon_edges_1
sbatch generate_partial_precomp_camelyon_edges_2
sbatch generate_partial_precomp_camelyon_edges_3
sbatch generate_partial_precomp_camelyon_edges_4

sbatch generate_partial_precomp_tcga_edges_1.slurm
sbatch generate_partial_precomp_tcga_edges_2.slurm
sbatch generate_partial_precomp_tcga_edges_3.slurm
sbatch generate_partial_precomp_tcga_edges_4.slurm

echo "All Queue'd"